### ISSUE TITLE
Chrome browser not supported

### ISSUE THREAD

**Issue by victorcouste** [knurl/bigbang#4]
Chrome browser not supported because of HTPPS and an invalid certificate

**Comment by victorcouste** [comment]
In fact, Chrome is not supported only when TLS is activated for both coordinator and internal communication

**Comment by knurl** [comment]
When using internal communication, a self-signed cert is used. Did you add this cert to Chrome? https://www.ateam-oracle.com/how-to-make-chrome-on-os-x-trust-a-self-signed-certificate

**Comment by knurl** [comment]
@victorcouste do you have an answer to this one?

**Comment by knurl** [comment]
No answer from @victorcouste so closing for now.

**Comment by victorcouste** [comment]
I didn't add this cert to Chrome, I will redo tests with the cert added
